# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Studio u by kingjakeu'
tagline:             'A Jekyll theme'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name                     : "jakeyoo"
  description              : "This is hello from jakeu"
  url                      : "https://kingjakeu.github.io"

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
paginate: 5
